### ISSUE TITLE
GPT-judge processing is missing

### ISSUE THREAD

**Issue by lshkanyun** [SmileWHC/CJEval#1]
Hi, thank you for proving this work on junior high school tasks.
I noticed that in the code, [the prompt to query GPT and get judgement](https://github.com/SmileWHC/CJEval/blob/0077ee9f9876aacb115d1249a24caa8479bc7b8d/code/generate_prompt.py#L74-L87) is given but is never used. And during the evaluation, [the result seems to have been processed](https://github.com/SmileWHC/CJEval/blob/0077ee9f9876aacb115d1249a24caa8479bc7b8d/code/evaluation.py#L161-L163). Can you provide the missing part? I.e. After I query GPT with the prompt and have a response, how can I get the final GPT judgement?

**Comment by SmileWHC** [comment]
Here’s a clear response to address this issue:

Hi,

Thank you for your interest in our work! In the evaluation of QA tasks, we used regex-based methods to evaluate multiple-choice and true/false questions. For open-ended or subjective questions like fill-in-the-blank or essay-style answers, we employed GPT prompts to assess responses.

To streamline the process, we pre-processed the evaluation by generating a results file before running the evaluation code to compute the final metrics. For the GPT-based evaluations, we constrained GPT outputs to either "正确" (Correct) or "不正确" (Incorrect), with the valid output used as the final GPT judgment.

If needed, we can consider updating and providing the pre-processed results files and corresponding code in a future release. Please let us know if you have any other questions or suggestions!

Best regards!
