### ISSUE TITLE
For QAs tasks, structured_answer is missing

### ISSUE THREAD

**Issue by lshkanyun** [SmileWHC/CJEval#2]
Hi there, I was try to produce the result and find that `structured_answer` is missing in json file but is [used in code](https://github.com/SmileWHC/CJEval/blob/0077ee9f9876aacb115d1249a24caa8479bc7b8d/code/run_task.py#L101).

By any change, can we attain this value somehow?

**Comment by SmileWHC** [comment]
Hi there,

Thanks for pointing this out! We have replaced structured_answer with ques_answer in the dataset. You can use ques_answer directly in the code. We'll update and optimize the code accordingly in the upcoming version.

Feel free to reach out if you have further questions!
